C
C     FORTICON8  JANUARY 2018
C     MATTHEW CLARK
C
      SUBROUTINE DELETS(S,COUL0,SORB,NDIM)
C
C  SUBROUTINE FOR SETTING CERTAIN OVERLAP INTEGRALS EQUAL TO ZERO.
C
      IMPLICIT REAL*8(A-H,O-Z)
      INCLUDE 'PARAMETERS'

      DIMENSION S(NDIM,NDIM),COUL0(NDIM),SORB(NDIM)
      INTEGER*4 COUL0
C      WAS INTEGER*2 HERE IN OLD CODE
      INTEGER*4 SORB
      COMMON/CNTRL/CON,PEEP,COULH,NH,NA,NATM,KA,NELEC,METH,IPRINT,
     1IPUNCH,L1,L2,L3,L4,L5,ONEMAT,ITERAT
      LOGICAL*1 L1,L2,L3,L4,L5,ONEMAT,ITERAT
      COMMON/OUT/PRT(20),PUN(20)
      LOGICAL*1 PRT,PUN
      LOGICAL*1 IERR
      CHARACTER*8 ORBTL, ATMPR, X1, X2
      DATA ORBTL/' ORBITAL'/,ATMPR/'  ATOM  '/
      SORB(NA+1)=NDIM+1
      IERR=.FALSE.
C
C  READ IN NUMBERS INDICATING WHICH OVERLAP INTEGRALS ARE TO BE SET
C  TO ZERO. A POSITIVE NUMBER REFERS TO AN ATOM, A NEGATIVE ONE TO
C  AN ORBITAL.
C
10    READ(5,1000,END=300) COUL0
1000  FORMAT(20I3)
      DO 200 IDEL=1,19,2
      I=COUL0(IDEL)
      J=COUL0(IDEL+1)
C
C  TERMINATE ON ENCOUNTERING A ZERO.
C
      IF(I.EQ.0.OR.J.EQ.0) GO TO 400
      IF(IERR) GO TO 200
      IABSV=IABS(I)
      JABSV=IABS(J)
      IF(I.GT.NH) GO TO 20
C
C  I REFERS TO ORBITAL (NEGATIVE) OR H ATOM (POSITIVE,LE NH).
C
      ILOW=IABSV
      IHIGH=IABSV
C
C  ERROR IF I OUT OF RANGE OF ORBITAL NUMBERS.
C
      IF(IABSV.GT.NDIM) GO TO 160
      GO TO 30
C
C  ERROR IF I OUT OF RANGE OF ATOMS.
C
20    IF(I.GT.NATM) GO TO 160
      ILOW=SORB(IABSV-NH)
      IHIGH=SORB(IABSV-NH+1)-1
30    IF(J.GT.NH) GO TO 40
      JLOW=JABSV
      JHIGH=JABSV
C
C  CHECK TO SEE IF J IS IN RANGE.
C
      IF(JABSV.GT.NDIM) GO TO 160
      GO TO 50
40    IF(J.GT.NATM) GO TO 160
      JLOW=SORB(JABSV-NH)
      JHIGH=SORB(JABSV-NH+1)-1
50    X1=ATMPR
      IF(I.LT.0) X1=ORBTL
      X2=ATMPR
      IF(J.LT.0) X2=ORBTL
      IF(.NOT.PRT(2)) WRITE(6,1002) X1,IABSV,X2,JABSV
1002  FORMAT('ALL S(I,J) SET TO ZERO BETWEEN',A8,I4,' AND',A8,I4,'.')
C
C  J MUST BE LESS THAN OR EQUAL TO I SINCE WE ONLY HAVE A HALF
C  MATRIX AT THIS POINT.
C
      IF(JHIGH.LE.IHIGH) GO TO 60
      I=JHIGH
      JHIGH=IHIGH
      IHIGH=I
      I=JLOW
      JLOW=ILOW
      ILOW=I
60    DO 100 I=ILOW,IHIGH
      DO 100 J=JLOW,JHIGH
100   S(J,I)=0.D0
      GO TO 200
160   IERR=.TRUE.
      WRITE(6,1003) COUL0
1003  FORMAT('NUMBER OUT OF RANGE IN FOLLOWING DELETION CARD'/'0',20I5/
     *'NO FURTHER DELETIONS, BUT SCANNING FOR ZERO TO TERMINATE CARD RE
     *ADING.')
200   CONTINUE
      GO TO 10
300   WRITE(6,1004)
1004  FORMAT('END OF FILE IN DELETION CARDS, NO FURTHER DELETIONS.')
400   RETURN
      END
