C
C     FORTICON8  JANUARY 2018
C     MATTHEW CLARK
C
      REAL*8 FUNCTION DOT(A,B)
      IMPLICIT REAL*8(A-H,O-Z)
      DIMENSION A(*),B(*)
      COMMON /VECTOR/ FACTOR,LIMIT
C
C    FUNCTION FOR USE IN GIVENS DIAGNOLIZATION PACKAGE.
C
      ITOP=LIMIT+1
      DOT=0.D0
      DO 10 I=1,ITOP
 10   DOT=DOT+A(I)*B(I)
      RETURN
      END
