C
C     FORTICON8  JANUARY 2018
C     MATTHEW CLARK
C
      SUBROUTINE PEGLEG2(AA,NN,NLL,IUNIT)
C
C     ROUTINE FOR WRITING OUT THE EIGENVECTORS TO DISK FILE 13 FOR
C     PLOTTING ROUTINES.   JJN  8-8-90
C
      IMPLICIT REAL*8(A-H,O-Z)
      DIMENSION AA(NLL,NLL)
      NROWW=NN
      NCOLL=NN
      DO 9997 I=1,NROWW
      DO 9997 J=1,NROWW
9997    WRITE(IUNIT,9998) AA(J,I)
C
C original
C       WRITE(IUNIT,9998) ((AA(J,I),J=1,NROWW), I=1,NCOLL)
C        WRITE(IUNIT,9998) ((AA(I,J),J=1,NROWW), I=1,NCOLL)
C      modified
C       WRITE(IUNIT,9998) ((AA(I,J),I=NCOLL,1,-1), J=1,NROWW)
9998  FORMAT(F10.6)
      CLOSE(IUNIT)

      RETURN
      END
