C
C     FORTICON8  JANUARY 2018
C     MATTHEW CLARK
C
      SUBROUTINE REDUCE(U,NDIM)
      IMPLICIT REAL*8(A-H,O-Z)
      INCLUDE 'PARAMETERS'

      DIMENSION U(NDIM,NDIM)

      COMMON/CNTRL/CON,PEEP,COULH,NH,NA,NATM,KA,NELEC,METH,IPRINT,
     1IPUNCH,L1,L2,L3,L4,L5,ONEMAT,ITERAT
      LOGICAL*1 L1,L2,L3,L4,L5,ONEMAT,ITERAT
 
      INCLUDE 'ATOMCOMMON'


C
C    SUBROUTINE TO CALCULATE REDUCED MATRIX.
C
      CALL REDCHM(U,NDIM)
      ISUB=NH+1
      IAO=ISUB
      DO 100 I=1,NA
      KEYI=KEY(I)
      IF(ND(KEYI)) 10,20,10
 10   IATOP=IAO+8
      GO TO 50
 20   IF(NP(KEYI)) 30,40,30
 30   IATOP=IAO+3
      GO TO 50
 40   IATOP=IAO
 50   DO 70 J=1,NATM
      SUM=0.D0
      DO 60 K=IAO,IATOP
      SUM=SUM+U(J,K)
 60   CONTINUE
      U(J,ISUB)=SUM
 70   CONTINUE
      ISUB=ISUB+1
 100  IAO=IATOP+1
      RETURN
      END
