C
C     FORTICON8  JANUARY 2018
C     MATTHEW CLARK
C
      SUBROUTINE TRNFRM(S,H,C,COUL0,NDIM,SP,IEXIT)
      IMPLICIT REAL*8(A-H,O-Z)
      INCLUDE 'PARAMETERS'

      DIMENSION S(NDIM,NDIM),H(NDIM,NDIM),
     .C((NDIM*NDIM+NDIM)/2),COUL0(NDIM),SP(NDIM)
      LOGICAL*1 ONEMAT
C
C    SUBROUTINE FOR CARRYING OUT A CHANGE IN BASIS SET ON A MATRIX H
C    BY MEANS OF A MATRIX U.
C
C                C=U'*H*U
C
C    H IS ASSUMED REAL SYMMETRIC AND ONLY THE LOWER LEFT TRIANGLE
C    IS REFERENCED. U IS ASSUMED TO BE ENTIRELY CONTAINED IN ITS
C    UPPER RIGHT TRIANGLE AND ONLY THIS PART IS REFERENCED. THE
C    RESULTING REAL SYMMETRIC MATRIX, C, IS STORED IN PACKED FORM.
C
C    INDEX1 OF LOOP1 POINTS TO U(1,J), J=1,NDIM
C    INDEX2 OF LOOP2 POINTS TO H(I,1), I=1,J
C    INDEX3 OF LOOP3 POINTS TO U(K,J), K=1,I
C    INDEX4 OF LOOP4 POINTS TO U(K,J), K=I+1,J
C    INDEX5 OF LOOP5 POINTS TO U(1,I), I=1,J
C    INDEX6 OF LOOP6 POINTS TO U(K,I), K=1,I
C
C     MATRIX C SIZE  MUST BE (NDIM**2 + NDIM)/2 
C
 
      ONEMAT=IEXIT.EQ.2.OR.IEXIT.EQ.3
      ISUB=1
      DO 100 J=1,NDIM
      DO 40 I=1,J
      SUM=0.D0
      ILIM=I
      IF(.NOT.ONEMAT) GO TO 10
      IF(I.LT.J) GO TO 10
      ILIM=I-1
C
C    IN THE ONE MATRIX CASE, THE S AND H MATRICES OVERLAP ALONG THE
C    DIAGONAL.  THE DIAGONAL OF S IS THEN PUT INTO SP.
C
      SUM=SP(I)*H(I,I)
      IF(I.EQ.1) GO TO 25
 10   DO 20 K=1,ILIM
 20   SUM=SUM+S(K,J)*H(I,K)
 25   IF(I.EQ.J) GO TO 40
      I1=I+1
      ILIM=J
      IF(.NOT.ONEMAT) GO TO 27
      ILIM=J-1
      SUM=SUM+SP(J)*H(J,I)
      IF(ILIM.LT.I1) GO TO 40
 27   DO 30 K=I1,ILIM
 30   SUM=SUM+S(K,J)*H(K,I)
 40   COUL0(I)=SUM
      DO 60 I=1,J
      SUM=0.D0
      ILIM=I
      IF(.NOT.ONEMAT) GO TO 45
      ILIM=I-1
      SUM=COUL0(I)*SP(I)
      IF(ILIM.EQ.0) GO TO 55
 45   DO 50 K=1,ILIM
 50   SUM=SUM+COUL0(K)*S(K,I)
 55   C(ISUB)=SUM
 60   ISUB=ISUB+1
 100  CONTINUE
      RETURN
      END
